services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - TZ=America/Denver
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy-network
      - aifred-network

networks:
  caddy-network:
    name: caddy-network
  aifred-network:
    external: true

volumes:
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config
